apiVersion: v1
kind: Service
metadata:
  namespace: flux-system
  name: sample-app
  labels:
    app: sample-app
spec:
  type: ClusterIP
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
